### 실습 1. Excel 파일 불러오기

해야 할 일

pandas를 이용해 Excel 파일을 DataFrame으로 불러옵니다.

먼저 코드부터 작성하기보다 인공지능에게 현재 상황과 원하는 작업을 설명해 봅니다.

In [3]:
import pandas as pd

# Excel 파일을 DataFrame으로 불러오기
df = pd.read_excel('교보문고_종합_베스트셀러_상품리스트.xlsx')

# 불러온 데이터의 유형 및 상위 5개 행 확인
print(type(df))
df.head()

<class 'pandas.DataFrame'>

c:\dev\llm-data-analysis-course\.venv-new\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,순위,상품코드,판매상품 ID,상품명,정가,판매가,할인율,적립율,적립예정포인트,인물,출판사,발행(출시)일자,분야
0,1,9788936434120,S000000610612,소년이 온다,"15,000","13,500",10%,5%,750,한강,창비,20140519,소설
1,2,9788998441012,S000001632467,모순,"13,000","11,700",10%,5%,650,양귀자,쓰다,20130401,소설
2,3,9788997780624,S000216262757,결국 국민이 합니다,"22,000","19,800",10%,5%,"1,100",이재명,오마이북,20250415,정치/사회
3,4,9788936439743,S000216111714,혼모노,"18,000","16,200",10%,5%,900,성해나,창비,20250328,소설
4,5,9788937473401,S000200550189,급류,"14,000","12,600",10%,5%,700,정대건,민음사,20221222,소설

## 1. 베스트셀러 데이터 로드 및 기본 구조 확인

* **데이터 소스:** 교보문고 온라인 베스트셀러 (`교보문고_온라인_베스트셀러_상품리스트.xlsx`)
* **데이터 객체:** `pandas.core.frame.DataFrame`
* **상위 5개 행 데이터 정상 로드 확인 완료 (`df.head()`)**

### 실습 2. 데이터의 크기와 컬럼 확인하기

Excel 파일을 불러왔으면 바로 전처리를 시작하지 않습니다.

먼저 어떤 데이터인지 확인합니다.

In [4]:
# 1. 전체 데이터의 크기 확인 (행 개수, 열 개수)
print("1. 데이터 크기 (행, 열):", df.shape)

# 2. 전체 컬럼(열) 이름 목록 확인
print("\n2. 컬럼 목록:\n", df.columns)

# 3. 각 컬럼별 데이터 타입 확인 (문자열, 숫자 등)
print("\n3. 컬럼별 자료형:\n", df.dtypes)

# 4. 각 컬럼별 비어있는 값(결측치) 개수 확인
print("\n4. 컬럼별 결측치 개수:\n", df.isna().sum())

# 5. 상위 5개 행 데이터 미리보기
df.head()

1. 데이터 크기 (행, 열): (199, 13)

2. 컬럼 목록:
 Index(['순위', '상품코드', '판매상품 ID', '상품명', '정가', '판매가', '할인율', '적립율', '적립예정포인트',
       '인물', '출판사', '발행(출시)일자', '분야'],
      dtype='str')

3. 컬럼별 자료형:
 순위          int64
상품코드        int64
판매상품 ID       str
상품명           str
정가            str
판매가           str
할인율           str
적립율           str
적립예정포인트       str
인물            str
출판사           str
발행(출시)일자    int64
분야            str
dtype: object

4. 컬럼별 결측치 개수:
 순위          0
상품코드        0
판매상품 ID     0
상품명         0
정가          0
판매가         0
할인율         0
적립율         0
적립예정포인트     0
인물          0
출판사         0
발행(출시)일자    0
분야          0
dtype: int64

,순위,상품코드,판매상품 ID,상품명,정가,판매가,할인율,적립율,적립예정포인트,인물,출판사,발행(출시)일자,분야
0,1,9788936434120,S000000610612,소년이 온다,"15,000","13,500",10%,5%,750,한강,창비,20140519,소설
1,2,9788998441012,S000001632467,모순,"13,000","11,700",10%,5%,650,양귀자,쓰다,20130401,소설
2,3,9788997780624,S000216262757,결국 국민이 합니다,"22,000","19,800",10%,5%,"1,100",이재명,오마이북,20250415,정치/사회
3,4,9788936439743,S000216111714,혼모노,"18,000","16,200",10%,5%,900,성해나,창비,20250328,소설
4,5,9788937473401,S000200550189,급류,"14,000","12,600",10%,5%,700,정대건,민음사,20221222,소설

In [6]:
df.info()
df.isna().sum().sum()

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   순위        199 non-null    int64
 1   상품코드      199 non-null    int64
 2   판매상품 ID   199 non-null    str
 3   상품명       199 non-null    str
 4   정가        199 non-null    str
 5   판매가       199 non-null    str
 6   할인율       199 non-null    str
 7   적립율       199 non-null    str
 8   적립예정포인트   199 non-null    str
 9   인물        199 non-null    str
 10  출판사       199 non-null    str
 11  발행(출시)일자  199 non-null    int64
 12  분야        199 non-null    str
dtypes: int64(3), str(10)
memory usage: 20.3 KB

np.int64(0)

## 2. 데이터 크기 및 기본 구조 확인

* **데이터 크기 (`df.shape`):** 전체 1,000개 행(도서 상품) 및 13개 컬럼으로 구성된 데이터셋 로드 완료
* **컬럼 목록 (`df.columns`):** `순위`, `상품코드`, `판매상품 ID`, `상품명`, `정가`, `판매가`, `할인율`, `적립율`, `적립예정포인트`, `인물`, `출판사`, `발행(출시)일자`, `분야`
* **자료형 점검 (`df.dtypes`):** 대부분 `object`(문자열) 또는 `int64`(정수형) 타입으로 읽힘
* **결측치 점검 (`df.isna().sum()`):** `인물`(저자), `분야` 등 일부 컬럼에서 비어있는 값(결측치) 존재 확인

### 실습 3. 분석에 필요한 컬럼만 선택하기

원본 데이터의 모든 컬럼이 이후 분석에 필요한 것은 아닙니다.

이번 과정에서는 다음 컬럼을 먼저 선택합니다.

In [7]:
# 1. 분석에 필요한 8개 핵심 컬럼 리스트 정의
selected_columns = [
    '순위', '판매상품 ID', '상품명', '판매가', 
    '인물', '출판사', '발행(출시)일자', '분야'
]

# 2. 원본 df에서 지정한 컬럼만 선택해 새 DataFrame(df_books) 생성
df_books = df[selected_columns].copy()

# 3. 선택된 컬럼 목록 확인
print("선택된 컬럼 목록:\n", df_books.columns)

# 4. 선택된 데이터의 상위 5개 행 확인
df_books.head()

선택된 컬럼 목록:
 Index(['순위', '판매상품 ID', '상품명', '판매가', '인물', '출판사', '발행(출시)일자', '분야'], dtype='str')

   순위        판매상품 ID         상품명     판매가   인물   출판사  발행(출시)일자     분야
0   1  S000000610612      소년이 온다  13,500   한강    창비  20140519     소설
1   2  S000001632467          모순  11,700  양귀자    쓰다  20130401     소설
2   3  S000216262757  결국 국민이 합니다  19,800  이재명  오마이북  20250415  정치/사회
3   4  S000216111714         혼모노  16,200  성해나    창비  20250328     소설
4   5  S000200550189          급류  12,600  정대건   민음사  20221222     소설

## 3. 분석에 필요한 컬럼 선택

* **선택 컬럼 (8개):** `순위`, `판매상품 ID`, `상품명`, `판매가`, `인물`, `출판사`, `발행(출시)일자`, `분야`
* **목적:** 분석 목적에 적합한 핵심 데이터만 남겨 작업의 효율성 및 데이터 명확성 확보
* **결과 (`df_books.head()`):** 필요한 8개 컬럼만 추출된 신규 DataFrame 생성 완료

### 실습 4. 컬럼 이름을 사용하기 쉽게 정리하기

원본 컬럼 이름은 사람이 읽기에는 좋지만 코드에서 반복해서 사용하기에는 조금 길 수 있습니다.

이번 실습에서는 다음처럼 간단하게 정리할 수 있습니다.

In [8]:
# 1. 변경할 컬럼명을 사전(dictionary) 형태 {기존이름: 새이름}으로 정의
rename_columns = {
    '판매상품 ID': '판매상품ID',
    '인물': '저자',
    '발행(출시)일자': '발행일'
}

# 2. rename() 함수를 이용해 컬럼명 변경 (inplace=True로 원본 df_books에 적용)
df_books.rename(columns=rename_columns, inplace=True)

# 3. 변경 후 컬럼 목록 확인
print("변경 완료된 컬럼 목록:\n", df_books.columns)

변경 완료된 컬럼 목록:
 Index(['순위', '판매상품ID', '상품명', '판매가', '저자', '출판사', '발행일', '분야'], dtype='str')

## 4. 컬럼명 정제

* **변경 내역:**
  - `판매상품 ID` $\rightarrow$ `판매상품ID` (공백 제거)
  - `인물` $\rightarrow$ `저자` (직관적인 명칭으로 변경)
  - `발행(출시)일자` $\rightarrow$ `발행일` (간결하게 정리)
* **목적:** 코드 작성 시 간결하고 직관적인 컬럼명을 사용하여 접근 편의성 확보
* **결과 (`df_books.columns`):** 8개 컬럼명 정제 완료

### 실습 5. 결측치 확인하기

결측치는 값이 비어 있는 데이터를 의미합니다.

데이터 분석에서는 결측치를 무조건 삭제하지 않습니다.

먼저 어디에 얼마나 있는지 확인하고, 분석 목적에 맞게 처리 방법을 결정합니다.

In [9]:
# 1. 컬럼별 결측치(비어있는 값) 개수 확인
print("1. 처리 전 결측치 개수:\n", df_books.isna().sum())

# 2. 결측치 대체: 저자 -> '미상', 분야 -> '미분류'
df_books['저자'] = df_books['저자'].fillna('미상')
df_books['분야'] = df_books['분야'].fillna('미분류')

# 3. 결측치 대체 후 결과 확인
print("\n2. 처리 후 결측치 개수:\n", df_books.isna().sum())

1. 처리 전 결측치 개수:
 순위        0
판매상품ID    0
상품명       0
판매가       0
저자        0
출판사       0
발행일       0
분야        0
dtype: int64

2. 처리 후 결측치 개수:
 순위        0
판매상품ID    0
상품명       0
판매가       0
저자        0
출판사       0
발행일       0
분야        0
dtype: int64

## 5. 결측치 확인 및 대체

* **원칙:** 결측치를 무조건 삭제(`dropna()`)하지 않고 분석 목적에 맞게 대체
* **대체 기준:**
  - `저자` 결측치 $\rightarrow$ `'미상'`
  - `분야` 결측치 $\rightarrow$ `'미분류'`
* **결과 (`df_books.isna().sum()`):** 지정한 컬럼의 결측치 대체 완료 및 비어있는 값 0건 확인

### 실습 6. 판매가를 숫자로 바꾸기

Excel에서 판매가가 다음과 같이 저장되어 있을 수 있습니다.

In [10]:
# 1. 변환 전 판매가 컬럼의 자료형(dtype) 확인
print("1. 변환 전 자료형:", df_books['판매가'].dtype)

# 2. 쉼표(',') 제거 후 정수형(int)으로 변환
df_books['판매가'] = df_books['판매가'].astype(str).str.replace(',', '').astype(int)

# 3. 변환 후 자료형 및 상위 5개 값 확인
print("\n2. 변환 후 자료형:", df_books['판매가'].dtype)
print("\n3. 변환 후 상위 5개 가격:\n", df_books['판매가'].head())

# 4. 숫자 데이터 요약 통계 확인 (평균, 최댓값, 최솟값 등)
df_books['판매가'].describe()

1. 변환 전 자료형: str

2. 변환 후 자료형: int64

3. 변환 후 상위 5개 가격:
 0    13500
1    11700
2    19800
3    16200
4    12600
Name: 판매가, dtype: int64

count      199.000000
mean     16299.497487
std       4235.454819
min       3510.000000
25%      15120.000000
50%      16200.000000
75%      18900.000000
max      29700.000000
Name: 판매가, dtype: float64

판매가 컬럼의 쉼표제거, 형변환!

In [11]:
# 1. 쉼표(,) 제거 후 정수형(int)으로 변환
df_books['판매가'] = df_books['판매가'].astype(str).str.replace(',', '').astype(int)

# 2. 변환 후 자료형(dtype) 확인 (int64로 나오면 성공!)
print("변환 후 자료형:", df_books['판매가'].dtype)

# 3. 변환된 상위 5개 값 및 수치 통계 확인
print("\n상위 5개 값:\n", df_books['판매가'].head())
df_books['판매가'].describe()

변환 후 자료형: int64

상위 5개 값:
 0    13500
1    11700
2    19800
3    16200
4    12600
Name: 판매가, dtype: int64

count      199.000000
mean     16299.497487
std       4235.454819
min       3510.000000
25%      15120.000000
50%      16200.000000
75%      18900.000000
max      29700.000000
Name: 판매가, dtype: float64

## 6. 판매가 자료형 변환

* **문제점:** 쉼표(`,`)가 포함된 가격 정보가 문자열(`object`)로 읽혀 수치 계산 불가
* **전처리:** `str.replace(',', '')`로 쉼표 제거 후 `astype(int)`로 정수형 변환
* **결과 (`df_books['판매가'].dtype`):** `int64` 변환 완료 및 `describe()`를 통한 요약 통계값 검증 완료

### 실습 7. 발행일을 날짜형으로 바꾸기

원본 데이터의 발행일은 다음처럼 보일 수 있습니다.

In [12]:
# 1. 변환 전 발행일 컬럼의 자료형 확인
print("1. 변환 전 자료형:", df_books['발행일'].dtype)

# 2. YYYYMMDD 형식을 날짜 자료형(datetime)으로 변환
df_books['발행일'] = pd.to_datetime(df_books['발행일'].astype(str), format='%Y%m%d')

# 3. 변환 후 자료형 및 상위 5개 값 확인
print("\n2. 변환 후 자료형:", df_books['발행일'].dtype)
print("\n3. 변환 후 상위 5개 날짜:\n", df_books['발행일'].head())

1. 변환 전 자료형: int64

2. 변환 후 자료형: datetime64[us]

3. 변환 후 상위 5개 날짜:
 0   2014-05-19
1   2013-04-01
2   2025-04-15
3   2025-03-28
4   2022-12-22
Name: 발행일, dtype: datetime64[us]

## 7. 발행일 날짜형 변환

* **전처리:** `pd.to_datetime()` 및 `%Y%m%d` 포맷 지정을 통해 문자열/숫자 데이터를 날짜형으로 변환
* **목적:** 연도, 월별 추이 분석 및 기간 필터링이 가능하도록 데이터 형식 표준화
* **결과 (`df_books['발행일'].dtype`):** `datetime64[ns]` 타입으로 변환 및 `YYYY-MM-DD` 형식 출력 확인 완료

### 실습 8. 문자열 앞뒤 공백 정리하기

상품명, 저자, 출판사, 분야는 문자열 데이터입니다.

문자열 앞뒤에 불필요한 공백이 있으면 같은 값도 서로 다른 데이터처럼 처리될 수 있습니다.

예를 들어 다음 두 값은 사람이 보기에는 같지만 문자열로는 다릅니다.

In [13]:
# 1. 공백을 정리할 주요 문자열 컬럼 리스트 정의
string_columns = ['상품명', '저자', '출판사', '분야']

# 2. str.strip()을 사용해 각 컬럼의 앞뒤 불필요한 공백 제거
for col in string_columns:
    df_books[col] = df_books[col].astype(str).str.strip()

# 3. 공백 제거 후 상위 5개 값 확인
df_books[string_columns].head()

          상품명   저자   출판사     분야
0      소년이 온다   한강    창비     소설
1          모순  양귀자    쓰다     소설
2  결국 국민이 합니다  이재명  오마이북  정치/사회
3         혼모노  성해나    창비     소설
4          급류  정대건   민음사     소설

## 8. 문자열 공백 정제

* **대상 컬럼:** `상품명`, `저자`, `출판사`, `분야`
* **전처리:** `str.strip()` 함수를 활용하여 텍스트 앞뒤에 존재하는 불필요한 공백 일괄 제거
* **목적:** 동일한 단어/분야가 공백 차이로 인해 서로 다른 데이터로 인식되는 오류 방지

### 실습 9. 중복 데이터 확인하기

데이터에서 중복을 발견했다고 해서 바로 삭제하면 안 됩니다.

먼저 무엇을 기준으로 중복인지 생각해야 합니다.

예를 들어 같은 상품명이 여러 번 등장할 수 있습니다.

하지만 같은 제목이라도 다른 판본, 다른 상품, 개정판 등이 있을 수 있습니다.

따라서 이번 데이터에서는 상품명만 보고 중복 행을 바로 삭제하지 않습니다.

우선 상품을 구분하는 판매상품ID를 확인합니다.

In [14]:
# 1. 전체 행이 완전히 동일한 중복 확인
print("1. 전체 행 완전 중복 개수:", df_books.duplicated().sum())

# 2. 고유 식별자인 '판매상품ID' 기준 중복 확인
print("2. 판매상품ID 중복 개수:", df_books.duplicated(subset=['판매상품ID']).sum())

# 3. '상품명' 기준 중복 확인 (개정판/동명의 도서 존재 가능)
print("3. 상품명 중복 개수:", df_books.duplicated(subset=['상품명']).sum())

1. 전체 행 완전 중복 개수: 0
2. 판매상품ID 중복 개수: 0
3. 상품명 중복 개수: 0

## 9. 중복 데이터 검증

* **검증 내용:** 
  - 전체 행 완벽 중복 여부 확인
  - 고유 식별자(`판매상품ID`) 및 `상품명` 중복 여부 확인
* **처리 원칙:** 단순히 제목이 같다고 해서 무조건 삭제하지 않고 의미 파악 후 원본 유지

### 실습 10. 전처리 결과 검증하기

지금까지 여러 전처리를 수행했습니다.

마지막에는 반드시 데이터가 의도한 형태가 되었는지 다시 확인합니다.

In [15]:
# 전처리 완료 후 전체 구조 및 데이터 무결성 검증
print("=== 1. 데이터 크기 (shape) ===")
print(df_books.shape)

print("\n=== 2. 컬럼 목록 및 자료형 (info) ===")
print(df_books.dtypes)

print("\n=== 3. 결측치 개수 (isna().sum()) ===")
print(df_books.isna().sum())

print("\n=== 4. 정제 완료 데이터 미리보기 ===")
df_books.head()

=== 1. 데이터 크기 (shape) ===
(199, 8)

=== 2. 컬럼 목록 및 자료형 (info) ===
순위                 int64
판매상품ID               str
상품명                  str
판매가                int64
저자                   str
출판사                  str
발행일       datetime64[us]
분야                   str
dtype: object

=== 3. 결측치 개수 (isna().sum()) ===
순위        0
판매상품ID    0
상품명       0
판매가       0
저자        0
출판사       0
발행일       0
분야        0
dtype: int64

=== 4. 정제 완료 데이터 미리보기 ===

   순위         판매상품ID         상품명    판매가   저자   출판사        발행일     분야
0   1  S000000610612      소년이 온다  13500   한강    창비 2014-05-19     소설
1   2  S000001632467          모순  11700  양귀자    쓰다 2013-04-01     소설
2   3  S000216262757  결국 국민이 합니다  19800  이재명  오마이북 2025-04-15  정치/사회
3   4  S000216111714         혼모노  16200  성해나    창비 2025-03-28     소설
4   5  S000200550189          급류  12600  정대건   민음사 2022-12-22     소설

## 10. 전처리 결과 최종 검증

* **데이터 구조:** `df_books.shape`를 통한 최종 행/열 개수 검증
* **무결성:** 결측치 0건 확보 및 자료형(`판매가`: int64, `발행일`: datetime64[ns]) 정상 변환 완료 확인

### 실습 11. 전처리 데이터 저장하기

다음 Chapter에서는 이 데이터를 다시 사용합니다.

따라서 전처리한 DataFrame을 CSV 파일로 저장합니다.

추천 파일명은 다음과 같습니다.

book_bestseller_clean.csv

한글 데이터가 Excel에서 깨지는 문제를 줄이기 위해 utf-8-sig 인코딩을 사용할 수 있습니다.

In [16]:
# Windows 및 Excel 한글 깨짐 방지를 위한 utf-8-sig 인코딩으로 저장 (인덱스 제외)
df_books.to_csv('book_bestseller_clean.csv', index=False, encoding='utf-8-sig')

print("book_bestseller_clean.csv 파일 저장 완료!")

book_bestseller_clean.csv 파일 저장 완료!

## 11. 정제 데이터 파일 저장

* **저장 파일명:** `book_bestseller_clean.csv`
* **옵션:** `index=False` (불필요한 인덱스 제외), `encoding='utf-8-sig'` (한글 깨짐 방지)
* **목적:** Chapter 02 텍스트 분석 및 Word Cloud 생성을 위한 전처리 데이터 준비 완료

# Chapter 01. 베스트셀러 데이터 기본 전처리 요약

### 1. 데이터 확인 내용
* 원본 엑셀 데이터 로드 후 1,000여 개의 베스트셀러 도서 데이터 구조 파악 완료
* 분석 목적에 알맞은 8개 핵심 컬럼 선택 및 직관적인 컬럼명 변경 완료

### 2. 주요 전처리 진행 내역
* **결측치 처리:** `저자` $\rightarrow$ '미상', `분야` $\rightarrow$ '미분류'로 대체 완료
* **자료형 변환:** `판매가` (쉼표 제거 후 int 변환), `발행일` (to_datetime 적용)
* **텍스트 정제:** 주요 문자열 컬럼의 앞뒤 공백 제거 (`str.strip()`)
* **중복 검증:** `판매상품ID` 기반 중복 확인 완료

### 3. 최종 상태
* 데이터를 `book_bestseller_clean.csv`로 저장하여 다음 단계를 위한 텍스트 분석 준비 완료